apiVersion: v1
kind: Service
metadata:
  name: kube-demo
  labels:
    name: kube-demo
spec:
  type: NodePort    #或使用 LoadBalancer
  ports:
  - port: 8090  #这里的端口和clusterIP 对应，供内部访问。
    targetPort: 8088 #端口一定要和container暴露出来的端口对应
    protocol: TCP
    nodePort: 32143   # 所有的节点都会开放此端口，此端口供外部调用。
  selector:
    app: demo # 名称与deployment中定义的app名称保持一致
